---

#
# This file is for the most high level apt configuration
# and bootstrapping possible. This also has the side
# effect upgrading the system before anything else
# is installed or configured.
#

- name: Include Ubuntu partner repository
  lineinfile:
    path: /etc/apt/sources.list
    regexp: '^(.*)(deb .*ubuntu.*partner)'
    state: present
    line: '\2'
    backrefs: yes
  when: ansible_distribution == 'Ubuntu'

# Update and upgrade all available packages
- name: Update APT keys
  shell: apt-key update
  become: yes

- name: Update APT
  apt: update_cache=yes cache_valid_time={{ apt_cache_valid_time }}
  become: yes
