---

- include: apt.yml
  become: yes
  become_user: root

- include: utilities.yml
  become: yes
  become_user: root

- include: configure.yml
  become: yes
  become_user: root

- include: pi-only.yml
  become: yes
  become_user: root
  when: ansible_lsb.id == "Raspbian"

- include: misc.yml
  become: yes
  become_user: root

- include: swapfile.yml
  become: yes
  become_user: root

- include: user-env.yml

- include: delete-bullshit.yml
  become: yes
  become_user: root

- include: borg.yml
  become: yes
  become_user: root
  when: borg_backup_enabled
