---

- import_tasks: apt.yml
  become: yes
  become_user: root

- import_tasks: utilities.yml
  become: yes
  become_user: root

- import_tasks: configure.yml
  become: yes
  become_user: root

- import_tasks: pi-only.yml
  become: yes
  become_user: root
  when: ansible_lsb.id == "Raspbian"

- import_tasks: misc.yml
  become: yes
  become_user: root

- import_tasks: swapfile.yml
  become: yes
  become_user: root

- import_tasks: user-env.yml

- import_tasks: delete-bullshit.yml
  become: yes
  become_user: root

- import_tasks: borg.yml
  become: yes
  become_user: root
  when: borg_backup_enabled
