---

- include: upgrade.yml
  become: yes
  become_user: root

- include: utilities.yml
  become: yes
  become_user: root

- include: pi-only.yml
  become: yes
  become_user: root
  when: ansible_nodename == "raspberrypi"

- name: Install ACL
  become: yes
  become_user: root
  apt: name=acl state=present

- include: user-env.yml
