---
#
# Update and upgrade all available packages
#

- name: Update APT keys
  shell: apt-key update
  become: yes

- name: Update APT
  apt: update_cache=yes cache_valid_time={{ apt_cache_valid_time }}
  become: yes
