---

- name: Disable screen startup message
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.screenrc"
    line: "startup_message off"
    create: yes
    state: present

- name: Make sure Vim config file exists
  file:
    path: "{{ ansible_env.HOME }}/.vimrc"
    state: file

- name: Vim configuration settings update
  lineinfile:
    create: yes
    dest: "{{ ansible_env.HOME }}/.vimrc"
    line: "{{ item }}"
    state: present
  with_items:
    - set tabstop=2
    - syntax on
    - colorscheme elflord

- name: Configure VIM (for root)
  become: yes
  become_user: root
  lineinfile:
    create: yes
    dest: "/root/.vimrc"
    line: "{{ item }}"
    state: present
  with_items:
    - set tabstop=2
    - syntax on
    - colorscheme elflord

- name: Generate SSH keys
  shell: ssh-keygen -b 2048 -t rsa -f {{ ansible_env.HOME }}/.ssh/id_rsa -q -N ""
  args:
    creates: "{{ ansible_env.HOME }}/.ssh/id_rsa"

- name: Generate SSH keys (root)
  shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
  become: yes
  become_user: root
  args:
    creates: "/root/.ssh/id_rsa"
