---

- name: Install useful libraries
  apt: name="{{ item }}"
  with_items:
    - python-dev

- name: 'Install necessary utilities (shared)'
  apt: "name={{ item }}"
  with_items:
    - bc
    - imagemagick
    - lsof
    - pv
    - python-mysqldb
    - python-pip
    - python-setuptools
    - screen
    - unzip
    - vim

- name: 'Utilities (Mint)'
  apt: name="{{ item }}" state=latest
  with_items:
    - locate
    - tree
    - whois
  when: ansible_distribution == 'Linux Mint'

- name: 'Utilities (Ubuntu 16.04)'
  apt: name="{{ item }}" state=latest
  with_items:
    - locate
    - tree
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: 'Utilities (Ubuntu 18.04)'
  apt: name="{{ item }}" state=latest
  with_items:
    - mlocate
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'

- name: Set VIM as default editor
  alternatives:
    name: editor
    path: /usr/bin/vim

- name: Install top-like programs
  apt: "name={{ item }}"
  with_items:
    - htop
    - iotop

- name: Install glances
  pip: name=glances

- name: Install build tools
  apt: "name={{ item }}"
  with_items:
    - git
