---

- name: Install useful libraries
  apt: name="{{ item }}"
  with_items:
    - python-dev

- name: 'Install necessary utilities (shared)'
  apt: "name={{ item }}"
  with_items:
    - bc
    - curl
    - imagemagick
    - lsof
    - pv
    - screen
    - unzip
    - vim
    - wget

- name: 'Python Utilities (Ubuntu 18.04)'
  apt:
    name: ['python-mysqldb', 'python-pip', 'python-setuptools']
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'

- name: 'Utilities (Mint)'
  apt: name="{{ item }}" state=latest
  with_items:
    - locate
    - tree
    - whois
  when: ansible_distribution == 'Linux Mint'

- name: 'Utilities (Ubuntu 16.04)'
  apt: name="{{ item }}" state=latest
  with_items:
    - locate
    - tree
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: 'Utilities (Ubuntu 18.04)'
  apt: name="{{ item }}" state=latest
  with_items:
    - mlocate
    - whois
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'

- name: Set VIM as default editor
  alternatives:
    name: editor
    path: /usr/bin/vim

- name: Install top-like programs
  apt: "name={{ item }}"
  with_items:
    - htop
    - iotop

- name: Install glances (Ubuntu 18.04)
  pip: name=glances
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'

- name: Install glances (Ubuntu 20.04)
  apt: name=glances
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

- name: Install build tools
  apt: "name={{ item }}"
  with_items:
    - git
