---

- name: Install useful libraries
  apt: name="{{ item }}"
  with_items:
    - python-dev

- name: Install necessary utilities
  apt: "name={{ item }}"
  with_items:
    - bc
    - locate
    - lsof
    - pv
    - python-mysqldb
    - python-pip
    - python-setuptools
    - screen
    - tree
    - unzip
    - vim

- name: Set VIM as default editor
  alternatives:
    name: editor
    path: /usr/bin/vim

- name: Install top-like programs
  apt: "name={{ item }}"
  with_items:
    - htop
    - iotop

- name: Install glances
  pip: name=glances

- name: Install build tools
  apt: "name={{ item }}"
  with_items:
    - git
