---

- name: Install necessary utilities
  apt: "name={{ item }}"
  with_items:
    - bc
    - locate
    - lsof
    - python-mysqldb
    - screen
    - unzip
    - vim

- name: Set VIM as default editor
  alternatives:
    name: editor
    path: /usr/bin/vim

- name: Install top-like programs
  apt: "name={{ item }}"
  with_items:
    - htop
    - iotop

- name: Install build tools
  apt: "name={{ item }}"
  with_items:
    - git
